services:
  accounts:
    image: "microservices-01/accounts:v1"
    container_name: accounts
    ports:
      - "8080:8080"
    networks:
      - proximagroup
  loans:
    image: "microservices-01/loans:v1"
    container_name: loans
    ports:
      - "8090:8090"
    networks:
      - proximagroup
  cards:
    image: "microservices-01/cards:v1"
    container_name: cards
    ports:
      - "9000:9000"
    networks:
      - proximagroup
networks:
  proximagroup:
    driver: "bridge"