services:
  accounts:
    image: "microservices-01/accounts:latest"
    container_name: accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - proximagroup
  loans:
    image: "microservices-01/loans:latest"
    container_name: loans
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - proximagroup
  cards:
    image: "microservices-01/cards:latest"
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - proximagroup
networks:
  proximagroup:
    driver: "bridge"