server:
    port: 8090
spring: 
 application:
  name: loans
 datasource:
  url: jdbc:h2:mem:test
  driver-class-name: org.h2.Driver
  username: sa
  password: ''
 jpa:
  hibernate:
    ddl-auto: update
  defer-datasource-initialization: true
  show-sql: true
 config:
  import: "optional:configserver:http://localhost:8071/"  
 rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"