server:
   port: 8090
spring: 
   application:
      name: loans
   datasource:
      #  url: jdbc:h2:mem:test
      #  driver-class-name: org.h2.Driver
      #  username: sa
      #  password: ''
      url: jdbc:mysql://localhost:3317/loansdb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQLDialect
   config:
      import: "optional:configserver:http://localhost:8071/"  
   rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"