server:
   port: 8090
spring: 
   application:
      name: loans
   datasource:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password: ''
#      url: jdbc:mysql://localhost:3317/loansdb
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   config:
      import: "optional:configserver:http://localhost:8071/"  
   rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
     env:
        enabled: true
  health:
     readinessstate:
       enabled: true
     livenessstate:
       enabled: true
  endpoint:
     health:
       probes:
         enabled: true     
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8070/eureka
info:
   app:
      name: "loans"
      description: "Microservizio che gestisce loans"
      version: "1.0.0"