networks:
  proximagroup:
    name: "proximagroup"
    driver: "bridge"
services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: "common-config.yml"
      service: "network-service"

  configserver:
    image: "configserver:v1"
    container_name: configserver
    ports:
     - "8071:8071"
    extends:
      file: "common-config.yml"
      service: "base-service"
    depends_on:
     rabbit:
      condition: service_healthy
    healthcheck:
       test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
       interval: 10s
       timeout: 5s
       retries: 10
       start_period: 10s
  
  accounts:
     image: "accounts:v1"
     container_name: accounts
     ports:
       - "8080:8080"
     extends:
       file: "common-config.yml"
       service: "microservice-service"
     environment:
       SPRING_APPLICATION_NAME: "accounts"
  cards:
     image: "cards:v1"
     container_name: cards
     ports:
          - "9000:9000"
     extends:
          file: "common-config.yml"
          service: "microservice-service"
     environment:
          SPRING_APPLICATION_NAME: "cards"
  loans:
      image: "loans:v1"
      container_name: loans
      ports:
        - "8090:8090"
      extends:
        file: "common-config.yml"
        service: "microservice-service"
      environment:
        SPRING_APPLICATION_NAME: "loans"
