networks:
   proximagroup:
      name: "proximagroup"
      driver: "bridge"
services:
   accountsdb:
      container_name: accountsdb
      ports:
         - 3306:3306
      environment:
         MYSQL_DATABASE: accountsdb
      extends:
         file: common-config.yml
         service: microservice-db
      volumes:
         - ../../db-data/accounts:/var/lib/mysql

   loansdb:
       container_name: loansdb
       ports:
         - 3308:3306
       environment:
         MYSQL_DATABASE: loansdb
       extends:
         file: common-config.yml
         service: microservice-db
       volumes:
         - ../../db-data/loans:/var/lib/mysql

   cardsdb:
      container_name: cardsdb
      ports:
      - 3307:3306
      environment:
         MYSQL_DATABASE: cardsdb
      extends:
         file: common-config.yml
         service: microservice-db
      volumes:
         - ../../db-data/cards:/var/lib/mysql


   rabbit:
      image: rabbitmq:3.13-management
      container_name: "rabbit"
      hostname: rabbitmq
      ports:
         - "5672:5672"
         - "15672:15672"
      healthcheck:
         test: rabbitmq-diagnostics check_port_connectivity
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 5s
      extends:
         file: "common-config.yml"
         service: "network-service"

   configserver:
      container_name: configserver
      image: "configserver:v1"
      build:
         context: "../../configserver/"
      ports:
         - "8071:8071"
      extends:
         file: "common-config.yml"
         service: "base-service"
      depends_on:
         rabbit:
            condition: service_healthy
      healthcheck:
         test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
       
   eurekaserver:
      container_name: eurekaserver
      image: "eurekaserver:v1"        
      build:
         context: "../../eurekaserver/"
      ports:
         - "8070:8070"
      extends:
         file: "common-config.yml"
         service: "network-service"
      depends_on:
         configserver:
            condition: service_healthy
      healthcheck:
         test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
      environment:
         SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  
   accounts:
      container_name: accounts
      image: "accounts:v1"
      build:
         context: "../../accounts/"
      ports:
       - "8080:8080"
      depends_on:
         accountsdb:
            condition: service_healthy
      extends:
       file: "common-config.yml"
       service: "microservice-service"
      environment:
       SPRING_APPLICATION_NAME: "accounts"
       SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
   cards:
     image: "cards:v1"
     container_name: cards
     build:
         context: "../../cards/"
     ports:
          - "9000:9000"
     depends_on:
      cardsdb:
         condition: service_healthy
     extends:
          file: "common-config.yml"
          service: "microservice-service"
     environment:
          SPRING_APPLICATION_NAME: "cards"
          SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
   loans:
      image: "loans:v1"
      container_name: loans
      build:
         context: "../../loans/"
      ports:
        - "8090:8090"
      depends_on:
         loansdb:
            condition: service_healthy
      extends:
        file: "common-config.yml"
        service: "microservice-service"
      environment:
        SPRING_APPLICATION_NAME: "loans"
        SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
