services:
   network-service:
     networks:
       - proximagroup

   base-service:
     extends: 
        service: network-service
     environment:
        SPRING_RABBITMQ_HOST: "rabbit"

   microservice-service:
     extends:
       service: "base-service"
     depends_on:
       eurekaserver:
         condition: service_healthy
     environment:
         SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: root
         SPRING_PROFILES_ACTIVE: "prod"
         SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
       
   microservice-db:
      extends:
         service: network-service
      image: mysql:8.4.2
      healthcheck:
         test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
         timeout: 10s
         retries: 10
         interval: 10s
         start_period: 10s
      environment:
         MYSQL_ROOT_PASSWORD: root