services:
   network-service:
     networks:
       - proximagroup

   base-service:
     extends: 
        service: network-service
     environment:
        SPRING_RABBITMQ_HOST: "rabbit"

   microservice-service:
     extends:
       service: "base-service"
     depends_on:
       configserver:
         condition: service_healthy
     environment:
       SPRING_PROFILES_ACTIVE: "prod"
       SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"